site_name: Community Psychology Student Wiki
site_url: https://gra3wy.github.io/
repo_url: https://github.com/gra3wy/gra3wy.github.io
site_dir: 'site'
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - navigation.footer
  language: en
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
extra:
   social:
     - icon: fontawesome/brands/discord 
       link: https://discord.gg/DhXS3xFAyk
       name: Community Psychology Students Discord
copyright: Copyright &copy; 2024 Community Psychology Students Worldwide

nav: 
  - Home: index.md
  - About this Wiki: 
      - Overview: about.md
      - How to Contribute: contribute.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
