site_name: Community Psychology Student Wiki
site_url: https://studentwiki.github.io/
repo_url: https://github.com/studentwiki/studentwiki.github.io
site_dir: 'site'
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - navigation.footer
  language: en
  palette:

    # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue grey
        accent: orange
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue grey
        accent: orange
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
 # icon:
    #tag:
    #  teach: bootstrap/backpack2

extra:
  tags:
    Teaching: teach
    Student Empowerment: empower
  social:
     - icon: fontawesome/brands/discord 
       link: https://discord.gg/DhXS3xFAyk
       name: Community Psychology Students Discord
  
copyright: Copyright &copy; 2024 Community Psychology Students Worldwide

nav: 
  - Home: index.md
  - About this Wiki: 
      - Overview: about.md
      - How to Contribute: contribute.md
      #- Tags: Extras/tags.md
  - Student Power:
      - Student Organising & Unions: Student-Power/student-organising.md
      - Grad School Statistics: Student-Power/student-stats.md
  - Teaching:
      - Graduate Student Instructors: Teaching/gradinstructors.md
      - Critical Educational Praxis: Teaching/critical-ed-praxis.md
      - Attacks on DEI in Higher Education: Teaching/attacks-dei-higher-ed.md
      - Resources: Teaching/teaching.md
  - Free Library: library.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - tags:
      tags_file: Extras/tags.md
